#!/usr/bin/env bash

cd "${BASH_SOURCE%/*}" || exit

echo "Linting package..."
$(npm bin)/semistandard --verbose "../lib/**/*.js" | $(npm bin)/snazzy

echo "Linting package specs..."
$(npm bin)/semistandard --verbose "../spec/**/*.js" | $(npm bin)/snazzy
